apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: prashanth2paramaah/solar-system:62-8047f03e4e441e6983e724b4c94295bed7e574f2
        name: solar-system
        ports: 
        - containerPort: 80
