apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: prashanth2paramaah/solar-system:53-0af95782dc24f3f4b25192b88b10d1aab9dda0df
        name: solar-system
        ports: 
        - containerPort: 80
