apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: prashanth2paramaah/solar-system:91-87e7f20ceea591de4a3ad8122878d8ccccc76026
        name: solar-system
        ports: 
        - containerPort: 80
