apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: prashanth2paramaah/solar-system:47-cf2bf3ee0c3427c4c20c4c1bd418400f8fb48f3b
        name: solar-system
        ports: 
        - containerPort: 80
