apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: prashanth2paramaah/solar-system:90-6a6f85b81d57e0ad096cafb8474f51a18e73b3c1
        name: solar-system
        ports: 
        - containerPort: 80
